### ISSUE TITLE
the difference of tessdata and  tessdata_best and  the difference langdata_lstm and langdata

### ISSUE THREAD

**Issue by PUYANG123** [Shreeshrii/tess5train-fonts#5]

**Comment by PUYANG123** [comment]
Hi,Shreeshrii
I found that resources are downloaded from different addresses，for example,wget https://raw.githubusercontent.com/tesseract-ocr/langdata_lstm/master/common.punc
cd eng
wget https://raw.githubusercontent.com/tesseract-ocr/langdata/master/eng/eng.punc
and 
wget -O eng.traineddata https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata
mkdir -p best
cd best
wget -O eng.traineddata https://github.com/tesseract-ocr/tessdata_best/raw/master/eng.traineddata
why

**Comment by Shreeshrii** [comment]
All these repos (langdata, langdata_lstm, tessdata, tessdata_best etc) are part of tesseract-ocr project.

My repo tries to make it easy for people to follow the tesstutorial given at https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00

**Comment by PUYANG123** [comment]
Why is ready data downloaded from the tessdata and extract LSTM model is downloaded from best traineddata?

**Comment by Shreeshrii** [comment]
tessdata is the folder where the required config files are there, eg. lstm.train which is required for training. tesseract also expects eng.traineddata to be there, otherwise you will get an error.

Only the lstm files from tessdata_best can be used to continue training. These are 'float' models. The others are converted to 'integer' for speed but cannot be used to continue training.

**Comment by Shreeshrii** [comment]
langdata repo has the language training data for version 3.04. when Ray wrote the tutorial only that was available and the text size was suitable for fine tuning.

**Comment by Shreeshrii** [comment]
Langdata_lstm has files for 4.00 training.
